[package]
name = "libdrm_amdgpu_sys"
version = "0.1.2"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["Umio Yasuno <coelacanth_dream@proton.me>"]
description = "libdrm_amdgpu bindings for Rust, and some methods ported from Mesa3D."
repository = "https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs"
keywords = ["amdgpu", "libdrm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []
buildtime_bindgen = ["bindgen", "pkg-config"]

[lib]
# name = "libdrm_amdgpu_sys"
path = "lib.rs"

[dependencies]
libc = { version = "^0.2", default-features = false }

[build-dependencies]
bindgen = { version = "0.59.0", optional = true }
pkg-config = { version = "0.3.25", optional = true }

[[example]]
name = "amdgpu_info"
required-features = ["std"]

[[example]]
name = "vbios_dump"
required-features = ["std"]

[[example]]
name = "gpu_metrics"
required-features = ["std"]
